name: simple CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        env:
          OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
        run: ./gradlew build

      - name: Run tests
        env:
          OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
        run: ./gradlew test

      - name: Run detekt
        env:
          OPENWEATHER_API: ${{ secrets.OPENWEATHER_API }}
        run: ./gradlew detekt
  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: .\gradlew.bat build

      - name: Run tests
        run: .\gradlew.bat test

      - name: Run detekt
        run: .\gradlew.bat detekt